using System;
using Serilog.Context;
using Wildcat.Milan.Shared.Dtos.Host;

namespace Wildcat.Milan.Host.Core;

/// <summary>
/// This is a helper class to make it easier to dispose of all of the disposables generated by LogContext.PushProperty
/// </summary>
public class EnrichLogs : IDisposable
{
    private readonly IDisposable _logContextGameId;
    private readonly IDisposable _logContextServiceId;
    private readonly IDisposable _logContextServiceName;

    private EnrichLogs(IDisposable logContextGameId, IDisposable logContextServiceId,
        IDisposable logContextServiceName)
    {
        _logContextGameId = logContextGameId;
        _logContextServiceId = logContextServiceId;
        _logContextServiceName = logContextServiceName;
    }

    public static EnrichLogs WithGlobalData(ServiceRequest request, string cloudRunServiceName)
    {
        var logContextGameId = LogContext.PushProperty("GameId", request.BackendId);
        var logContextServiceId = LogContext.PushProperty("ServiceId", request.ServiceId);
        var logContextServiceName = string.IsNullOrEmpty(cloudRunServiceName)
            ? null
            : LogContext.PushProperty("CloudServiceName", cloudRunServiceName);

        return new EnrichLogs(logContextGameId, logContextServiceId, logContextServiceName);
    }

    public void Dispose()
    {
        _logContextGameId?.Dispose();
        _logContextServiceId?.Dispose();
        _logContextServiceName?.Dispose();
    }
}