version: '3'

services:
    mongo-server:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=password
            - MONGO_INITDB_DATABASE=local-milan-database
        ports:
            - "27017:27017"
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo-server
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            - ME_CONFIG_MONGODB_AUTH_USERNAME=mongoadmin
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
            - ME_CONFIG_BASICAUTH_USERNAME=mongoadmin
            - ME_CONFIG_BASICAUTH_PASSWORD=password
        depends_on:
            - mongo-server
        ports:
          - "8888:8081"
